[vars]
# ============================================
# 🔑 اینا مال اکانت خودته (سلف‌بری)
# ============================================

PHONE_NUMBER = "+989378038736"  # 👈 شماره خودت
API_ID = "3516317"              # 👈 از my.telegram.org
API_HASH = "5bb2948db3031dda29858104ada18631"  # 👈 از my.telegram.org
PASSWORD = ""                   # 👈 اگه پسورد داری

# ============================================
# 🤖 اینم ربات کنترل‌کننده (از @BotFather)
# ============================================

BOT_TOKEN = "8568499654:AAFyLZs7Ex9XzIy3wCUb9l9_gYQ2B_rF-Ss"
ADMIN_IDS = "5989309344"  # 👈 ایدی خودت
