name = "sara-self-bot"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "aed539a1686d4cff8579f90d365f3352"
preview_id = "aed539a1686d4cff8579f90d365f3352"

[ai]
binding = "AI"

[vars]
BOT_TOKEN = "8568499654:AAFyLZs7Ex9XzIy3wCUb9l9_gYQ2B_rF-Ss"
ADMIN_TOKEN = "Sara@HyperFul#1403"
API_ID = "3516317"
API_HASH = "5bb2948db3031dda29858104ada18631"
PHONE_NUMBER = "+989378038736"
PASSWORD = ""
ADMIN_IDS = "5989309344"

# ⚠️ این دو رو پر کن:
CF_ACCOUNT_ID = "your_cloudflare_account_id_here"
CF_API_TOKEN = "your_cloudflare_api_token_here"

MANAGER_ACCOUNTS = '[{"name":"مدیر","phone":"+989378038736"}]'

[triggers]
crons = ["0 0 * * *"]
